import csv
import json
import os
import shutil
import time
from collections import Counter, OrderedDict, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from statistics import median
from typing import Iterable

from scripts.merge_and_clean_datasets import (
    content_fingerprint,
    format_only_reason,
    is_weak_issue_summary,
    normalize_file_text,
    validate_grouped_dataset,
)

from .cli import PendingOutputSample, _build_output_sample, _classify_file_entities, _deduplicate_samples
from .diff_extractor import (
    commit_has_javadoc_and_code_changes,
    commit_has_javadoc_changes,
    extract_file_changes,
    parse_changed_paths,
)
from .git_repo import GitCommandError, GitRepo
from .issue_finder import commit_summary_with_fallback, find_issues
from .java_parser import parse_entities
from .models import FileChange, OutputSample
from .repositories import RepositorySpec, repository_slug
from .text_utils import is_low_signal_commit_message
from .validation import validate_code_snippet, validate_output_sample


CHANGE_FIELDS = (
    "change_index",
    "entity_type",
    "code_before",
    "code_after",
    "javadoc_before",
    "javadoc_after",
)
COMMIT_FIELDS = ("project_slug", "repository_url", "commit_hash", "issue_summary", "changes")
BATCH_FIELDS = (
    "project_slug",
    "repository_url",
    "batch_index",
    "commits_scanned",
    "cumulative_commits_scanned",
    "raw_candidate_commits",
    "raw_candidate_changes",
    "retained_commits_before_global_dedup",
    "retained_commits_after_global_dedup",
    "retained_changes_before_global_dedup",
    "retained_changes_after_global_dedup",
    "method_level_changes",
    "class_level_changes",
    "commits_with_multiple_changes",
    "duplicate_changes_removed",
    "empty_commits_removed",
    "format_only_rejection_count",
    "weak_issue_detected",
    "weak_issue_resolved",
    "weak_issue_unresolved",
    "java_parse_success_count",
    "java_parse_failure_count",
    "issue_summary_success_rate",
    "java_parse_success_rate",
    "yield_per_1000_scanned_commits",
    "oldest_commit",
    "newest_commit",
    "scan_status",
    "stop_reason",
)
PRODUCTION_HEADERS = ("generated", "auto-generated", "do not edit", "generated by")
METADATA_ONLY_COMMIT_SUBSTRINGS = (
    "license header",
    "license headers",
    "copyright header",
    "copyright headers",
    "copyright notice",
    "copyright notices",
    "apache header",
    "apache headers",
    "url cleanup",
)
LOW_YIELD_THRESHOLD = 3.0
HIGH_YIELD_THRESHOLD = 10.0


PRIORITY_REPOSITORIES = (
    RepositorySpec("google/guava", "https://github.com/google/guava.git"),
    RepositorySpec("junit-team/junit-framework", "https://github.com/junit-team/junit-framework.git"),
    RepositorySpec("mockito/mockito", "https://github.com/mockito/mockito.git"),
    RepositorySpec("assertj/assertj", "https://github.com/assertj/assertj.git"),
    RepositorySpec(
        "spring-projects/spring-data-commons",
        "https://github.com/spring-projects/spring-data-commons.git",
    ),
    RepositorySpec("JodaOrg/joda-time", "https://github.com/JodaOrg/joda-time.git"),
    RepositorySpec("google/gson", "https://github.com/google/gson.git"),
    RepositorySpec("ben-manes/caffeine", "https://github.com/ben-manes/caffeine.git"),
    RepositorySpec("ReactiveX/RxJava", "https://github.com/ReactiveX/RxJava.git"),
    RepositorySpec("reactor/reactor-core", "https://github.com/reactor/reactor-core.git"),
    RepositorySpec("micrometer-metrics/micrometer", "https://github.com/micrometer-metrics/micrometer.git"),
    RepositorySpec("OpenFeign/feign", "https://github.com/OpenFeign/feign.git"),
    RepositorySpec("FasterXML/jackson-core", "https://github.com/FasterXML/jackson-core.git"),
    RepositorySpec("FasterXML/jackson-annotations", "https://github.com/FasterXML/jackson-annotations.git"),
    RepositorySpec("FasterXML/jackson-modules-java8", "https://github.com/FasterXML/jackson-modules-java8.git"),
    RepositorySpec("FasterXML/jackson-dataformats-text", "https://github.com/FasterXML/jackson-dataformats-text.git"),
    RepositorySpec("grpc/grpc-java", "https://github.com/grpc/grpc-java.git"),
    RepositorySpec("TNG/ArchUnit", "https://github.com/TNG/ArchUnit.git"),
    RepositorySpec("netty/netty", "https://github.com/netty/netty.git"),
    RepositorySpec("spring-projects/spring-framework", "https://github.com/spring-projects/spring-framework.git"),
    RepositorySpec(
        "eclipse-collections/eclipse-collections",
        "https://github.com/eclipse-collections/eclipse-collections.git",
    ),
    RepositorySpec("mapstruct/mapstruct", "https://github.com/mapstruct/mapstruct.git"),
    RepositorySpec("raphw/byte-buddy", "https://github.com/raphw/byte-buddy.git"),
    RepositorySpec("undertow-io/undertow", "https://github.com/undertow-io/undertow.git"),
    RepositorySpec("apache/avro", "https://github.com/apache/avro.git"),
    RepositorySpec("apache/calcite", "https://github.com/apache/calcite.git"),
    RepositorySpec("apache/kafka", "https://github.com/apache/kafka.git"),
    RepositorySpec("jOOQ/jOOQ", "https://github.com/jOOQ/jOOQ.git"),
)


@dataclass(frozen=True)
class CommitContinuationConfig:
    root_dir: Path = Path(".")
    baseline_dir: Path = Path("final_dataset_merged_no_commit_cap")
    legacy_merged_dir: Path = Path("final_dataset_merged")
    continuation_dir: Path = Path("final_dataset_continuation_to_5k_commits")
    final_dir: Path = Path("final_dataset_5k_commits")
    cache_dir: Path = Path(".cache/repos")
    target_commits: int = 5000
    batch_size: int = 1000
    initial_probe_commits: int = 3000
    start_from: str = ""
    max_repos: int | None = None
    max_commits_per_repo: int | None = None
    smoke_commits: int = 0
    dry_run: bool = False
    force_refresh: bool = False
    fetch_existing: bool = False
    include_completed: bool = False


@dataclass
class ProjectCounters:
    commits_scanned: int = 0
    raw_candidate_commits: int = 0
    raw_candidate_changes: int = 0
    retained_commits_before_global_dedup: int = 0
    retained_changes_before_global_dedup: int = 0
    method_level_changes: int = 0
    class_level_changes: int = 0
    commits_with_multiple_changes: int = 0
    format_only_rejection_count: int = 0
    weak_issue_detected: int = 0
    weak_issue_resolved: int = 0
    weak_issue_unresolved: int = 0
    java_parse_success_count: int = 0
    java_parse_failure_count: int = 0
    moved_to_review: int = 0
    invalid_changes: int = 0
    newest_commit: str = ""
    oldest_commit: str = ""


def mine_commit_continuation_dataset(
    config: CommitContinuationConfig,
    repositories: Iterable[RepositorySpec] | None = None,
) -> dict:
    root_dir = config.root_dir
    baseline_dir = _resolve(root_dir, config.baseline_dir)
    continuation_dir = _resolve(root_dir, config.continuation_dir)
    final_dir = _resolve(root_dir, config.final_dir)
    cache_dir = _resolve(root_dir, config.cache_dir)
    legacy_merged_dir = _resolve(root_dir, config.legacy_merged_dir)
    baseline = _load_grouped_dataset(baseline_dir / "combined_by_commit.json")
    if not baseline:
        raise FileNotFoundError(f"No grouped baseline found in {baseline_dir}")

    specs = _selected_repositories(list(repositories or PRIORITY_REPOSITORIES), config.start_from, config.max_repos)
    completed_existing = _completed_existing_repositories(root_dir)
    baseline_keys = {(item["project_slug"], item["commit_hash"]) for item in baseline}
    _ensure_run_files(continuation_dir)
    current_outputs = refresh_commit_outputs(
        baseline=baseline,
        continuation_dir=continuation_dir,
        final_dir=final_dir,
        baseline_dir=baseline_dir,
        legacy_merged_dir=legacy_merged_dir,
        config=config,
    )

    print("5k commit continuation plan")
    print(f"- baseline grouped commits: {len(baseline)}")
    print(f"- current final commits after existing continuation merge: {current_outputs['summary']['final_commit_count']}")
    print(f"- target final commits: {config.target_commits}")
    print(f"- continuation output: {continuation_dir}")
    print(f"- final output: {final_dir}")
    print("- repositories in order:")
    for spec in specs:
        status = "completed-baseline-skip" if spec.slug in completed_existing and not config.include_completed else "scan"
        print(f"  - {spec.name}: {status}")
    if config.dry_run:
        return current_outputs["summary"]

    for spec in specs:
        if current_outputs["summary"]["final_commit_count"] >= config.target_commits:
            break
        if spec.slug in completed_existing and not config.include_completed:
            _record_skipped_repository(continuation_dir, spec, completed_existing[spec.slug])
            continue
        try:
            _mine_one_project(
                spec=spec,
                config=config,
                cache_dir=cache_dir,
                continuation_dir=continuation_dir,
                baseline_keys=baseline_keys,
                baseline=baseline,
                baseline_dir=baseline_dir,
                legacy_merged_dir=legacy_merged_dir,
                final_dir=final_dir,
            )
            current_outputs = refresh_commit_outputs(
                baseline=baseline,
                continuation_dir=continuation_dir,
                final_dir=final_dir,
                baseline_dir=baseline_dir,
                legacy_merged_dir=legacy_merged_dir,
                config=config,
            )
        except (GitCommandError, OSError) as error:
            _append_json_list(
                continuation_dir / "failed_repositories.json",
                {
                    "project_slug": spec.slug,
                    "repository_url": spec.url,
                    "error": str(error),
                    "failed_at_utc": _utc_now(),
                },
            )
            print(f"Failed {spec.name}: {error}")

    current_outputs = refresh_commit_outputs(
        baseline=baseline,
        continuation_dir=continuation_dir,
        final_dir=final_dir,
        baseline_dir=baseline_dir,
        legacy_merged_dir=legacy_merged_dir,
        config=config,
    )
    return current_outputs["summary"]


def refresh_commit_outputs(
    *,
    baseline: list[dict],
    continuation_dir: Path,
    final_dir: Path,
    baseline_dir: Path,
    legacy_merged_dir: Path,
    config: CommitContinuationConfig,
) -> dict:
    new_raw = _load_all_project_commits(continuation_dir)
    merged = _merge_grouped_commits(baseline, new_raw)
    _write_continuation_top_level(continuation_dir, new_raw, merged)
    _write_final_outputs(final_dir, merged, continuation_dir, baseline_dir, legacy_merged_dir, config)
    return merged


def _mine_one_project(
    *,
    spec: RepositorySpec,
    config: CommitContinuationConfig,
    cache_dir: Path,
    continuation_dir: Path,
    baseline_keys: set[tuple[str, str]],
    baseline: list[dict],
    baseline_dir: Path,
    legacy_merged_dir: Path,
    final_dir: Path,
) -> None:
    print(f"Scanning {spec.name}...")
    repo = GitRepo.clone_or_update(
        spec.url,
        cache_dir,
        force_refresh=config.force_refresh,
        fetch_existing=config.fetch_existing,
    )
    commit_hashes = _commit_hashes(repo)
    if config.smoke_commits:
        commit_hashes = commit_hashes[: config.smoke_commits]
    elif config.max_commits_per_repo is not None:
        commit_hashes = commit_hashes[: config.max_commits_per_repo]

    project_dir = continuation_dir / "per_project" / spec.slug
    project_dir.mkdir(parents=True, exist_ok=True)
    checkpoint = _read_json(project_dir / "checkpoint.json", {})
    processed = set(checkpoint.get("processed_commit_hashes", []))
    retained_commits = _load_grouped_dataset(project_dir / "cleaned_by_commit.json")
    retained_by_hash = {item["commit_hash"]: item for item in retained_commits}
    counters = _load_project_counters(checkpoint)
    batch_start_scanned = counters.commits_scanned
    batch_index = int(checkpoint.get("current_batch", 0) or 0) + 1
    stop_reason = ""
    scan_status = "partial"

    for commit_hash in commit_hashes:
        if commit_hash in processed:
            continue
        if (spec.slug, commit_hash) in baseline_keys and not config.include_completed:
            processed.add(commit_hash)
            counters.commits_scanned += 1
            _save_checkpoint(project_dir, spec, checkpoint, counters, processed, commit_hash, batch_index, "partial", "")
            continue
        counters.commits_scanned += 1
        if not counters.newest_commit:
            counters.newest_commit = commit_hash
        counters.oldest_commit = commit_hash
        commit = _extract_commit_object(repo, spec, commit_hash, counters, project_dir)
        if commit is not None:
            retained_by_hash[commit_hash] = commit
            counters.retained_commits_before_global_dedup = len(retained_by_hash)
            counters.retained_changes_before_global_dedup = sum(len(item["changes"]) for item in retained_by_hash.values())
            counters.method_level_changes = sum(
                1
                for item in retained_by_hash.values()
                for change in item["changes"]
                if change["entity_type"] == "method"
            )
            counters.class_level_changes = sum(
                1
                for item in retained_by_hash.values()
                for change in item["changes"]
                if change["entity_type"] == "class"
            )
            counters.commits_with_multiple_changes = sum(1 for item in retained_by_hash.values() if len(item["changes"]) > 1)
            _write_project_commit_files(project_dir, list(retained_by_hash.values()))

        processed.add(commit_hash)
        _save_checkpoint(project_dir, spec, checkpoint, counters, processed, commit_hash, batch_index, "partial", "")

        scanned_this_batch = counters.commits_scanned - batch_start_scanned
        if scanned_this_batch >= config.batch_size:
            outputs = refresh_commit_outputs(
                baseline=baseline,
                continuation_dir=continuation_dir,
                final_dir=final_dir,
                baseline_dir=baseline_dir,
                legacy_merged_dir=legacy_merged_dir,
                config=config,
            )
            _record_scan_progress(
                continuation_dir,
                spec,
                counters,
                outputs,
                batch_index,
                scanned_this_batch,
                "partial",
                "",
            )
            if outputs["summary"]["final_commit_count"] >= config.target_commits:
                stop_reason = f"target_commits={config.target_commits} reached"
                scan_status = "stopped"
                break
            retained_after = _retained_new_counts_for_project(outputs["grouped"], spec.slug)
            if _should_stop_low_yield(counters, config.initial_probe_commits, retained_after["commits"]):
                stop_reason = "low_yield"
                scan_status = "stopped"
                _append_json_list(
                    continuation_dir / "stopped_low_yield_repositories.json",
                    _repository_yield_row(spec, counters, "stopped", stop_reason, retained_after["commits"], retained_after["changes"]),
                )
                break
            batch_start_scanned = counters.commits_scanned
            batch_index += 1

    else:
        scan_status = "completed" if counters.commits_scanned >= len(commit_hashes) else "partial"
        if config.smoke_commits:
            stop_reason = f"smoke_commits={config.smoke_commits} reached"
        elif config.max_commits_per_repo is not None and counters.commits_scanned >= config.max_commits_per_repo:
            stop_reason = f"max_commits_per_repo={config.max_commits_per_repo} reached"
        else:
            stop_reason = "full_history_scanned" if scan_status == "completed" else "history_incomplete"

    _write_project_commit_files(project_dir, list(retained_by_hash.values()))
    outputs = refresh_commit_outputs(
        baseline=baseline,
        continuation_dir=continuation_dir,
        final_dir=final_dir,
        baseline_dir=baseline_dir,
        legacy_merged_dir=legacy_merged_dir,
        config=config,
    )
    final_batch_size = max(0, counters.commits_scanned - batch_start_scanned)
    if final_batch_size or not _read_json(continuation_dir / "scan_progress.json", []):
        _record_scan_progress(
            continuation_dir,
            spec,
            counters,
            outputs,
            batch_index,
            final_batch_size,
            scan_status,
            stop_reason,
        )
    _save_checkpoint(project_dir, spec, checkpoint, counters, processed, checkpoint.get("last_processed_commit", ""), batch_index, scan_status, stop_reason)
    _update_repository_yield_summary(continuation_dir)
    print(
        f"{spec.name}: scanned={counters.commits_scanned}, "
        f"retained_commits_before_global_dedup={counters.retained_commits_before_global_dedup}, "
        f"yield={_yield_per_1000(counters):.2f}, status={scan_status}, stop_reason={stop_reason}"
    )


def _extract_commit_object(
    repo: GitRepo,
    spec: RepositorySpec,
    commit_hash: str,
    counters: ProjectCounters,
    project_dir: Path,
) -> dict | None:
    try:
        changed_paths = parse_changed_paths(repo.show_name_status(commit_hash))
    except GitCommandError:
        return None
    if not changed_paths:
        return None
    try:
        commit_message = repo.commit_message(commit_hash)
    except GitCommandError:
        return None
    if is_low_signal_commit_message(commit_message):
        counters.weak_issue_detected += 1
        counters.weak_issue_unresolved += 1
        _append_json_list(
            project_dir / "unresolved_issue_summary.json",
            {
                "commit_hash": commit_hash,
                "issue_summary": commit_message.splitlines()[0] if commit_message else "",
                "reason": "low_signal_commit_message",
            },
        )
        return None
    if _is_metadata_only_commit_message(commit_message):
        counters.format_only_rejection_count += 1
        return None
    try:
        patch = repo.show_commit_patch(commit_hash)
    except GitCommandError:
        return None
    if not commit_has_javadoc_changes(patch):
        return None
    if not commit_has_javadoc_and_code_changes(patch):
        return None
    try:
        file_changes = extract_file_changes(repo, commit_hash, changed_paths)
    except GitCommandError:
        return None

    issues = find_issues(commit_message)
    pending: list[PendingOutputSample] = []
    for file_change in file_changes:
        if not _path_allowed_for_project(spec.name, file_change.path):
            continue
        if _is_generated_source(file_change.old_content) or _is_generated_source(file_change.new_content):
            continue
        try:
            old_entities = parse_entities(file_change.old_content or "")
            new_entities = parse_entities(file_change.new_content or "")
            counters.java_parse_success_count += 1
        except Exception as error:  # pragma: no cover - defensive against parser edge cases
            counters.java_parse_failure_count += 1
            _append_json_list(
                project_dir / "invalid_changes.json",
                {
                    "commit_hash": commit_hash,
                    "file_path": file_change.path,
                    "reason": f"java_parse_failure:{error}",
                },
            )
            continue
        for old_entity, new_entity, classification in _classify_file_entities(old_entities, new_entities, file_change):
            pending.append(
                PendingOutputSample(
                    commit_hash=commit_hash,
                    commit_message=commit_message,
                    issue_ids=issues,
                    file_change=file_change,
                    old_entity=old_entity,
                    new_entity=new_entity,
                    classification=classification,
                )
            )
    if not pending:
        return None
    counters.raw_candidate_commits += 1
    counters.raw_candidate_changes += len(pending)

    issue_summary, fallback_applied = commit_summary_with_fallback(commit_message)
    if is_weak_issue_summary(issue_summary):
        counters.weak_issue_detected += 1
        counters.weak_issue_unresolved += 1
        _append_json_list(
            project_dir / "unresolved_issue_summary.json",
            {
                "commit_hash": commit_hash,
                "issue_summary": issue_summary,
                "detected": True,
                "resolved": False,
                "resolution_source": "",
                "reason": "weak_issue_summary_unresolved",
            },
        )
        return None
    if fallback_applied:
        counters.weak_issue_detected += 1
        counters.weak_issue_resolved += 1

    samples: list[OutputSample] = []
    for candidate in _deduplicate_samples(pending):
        issue_id = candidate.issue_ids[0] if candidate.issue_ids else ""
        try:
            sample = _build_output_sample(
                repo=repo,
                commit_hash=commit_hash,
                commit_message=commit_message,
                issue_id=issue_id,
                issue_summary=issue_summary,
                file_change=candidate.file_change,
                old_entity=candidate.old_entity,
                new_entity=candidate.new_entity,
                classification=candidate.classification,
                issue_summary_fallback_applied=fallback_applied,
            )
        except ValueError:
            continue
        validation = validate_output_sample(sample)
        if validation.disposition == "retain":
            samples.append(sample)
        elif validation.disposition == "review":
            counters.moved_to_review += 1
            _append_json_list(
                project_dir / "entity_type_review.json",
                {"commit_hash": commit_hash, "reason": validation.reason, "file_path": sample.file_path},
            )
        else:
            counters.invalid_changes += 1
            _append_json_list(
                project_dir / "invalid_changes.json",
                {"commit_hash": commit_hash, "reason": validation.reason, "file_path": sample.file_path},
            )
    if not samples:
        return None
    return {
        "project_slug": spec.slug,
        "repository_url": spec.url,
        "commit_hash": commit_hash,
        "issue_summary": issue_summary,
        "changes": [
            {
                "change_index": index,
                "entity_type": sample.entity_type,
                "code_before": sample.code_before,
                "code_after": sample.code_after,
                "javadoc_before": sample.javadoc_before,
                "javadoc_after": sample.javadoc_after,
            }
            for index, sample in enumerate(samples, start=1)
        ],
    }


def _merge_grouped_commits(baseline: list[dict], new_commits: list[dict]) -> dict:
    raw_flat = _flatten_grouped(baseline, "baseline") + _flatten_grouped(new_commits, "new")
    cleaned: list[dict] = []
    removed_format_only: list[dict] = []
    invalid_changes: list[dict] = []
    entity_type_review: list[dict] = []
    unresolved_issue_summary: list[dict] = []
    for change in raw_flat:
        clean, reason = _clean_flat_change(change)
        if clean is None:
            target = entity_type_review if reason == "unknown_entity_type" else invalid_changes
            target.append(_audit_removed_change(change, reason))
            continue
        format_reason = format_only_reason(clean["javadoc_before"], clean["javadoc_after"])
        if format_reason:
            removed_format_only.append(_audit_removed_change(clean, format_reason))
            continue
        cleaned.append(clean)

    seen: dict[str, dict] = {}
    deduped: list[dict] = []
    removed_duplicates: list[dict] = []
    for change in cleaned:
        fingerprint = content_fingerprint(change)
        if fingerprint in seen:
            removed_duplicates.append(
                {
                    **_audit_removed_change(change, "duplicate_change"),
                    "duplicate_of": _change_ref(seen[fingerprint]),
                }
            )
            continue
        seen[fingerprint] = change
        deduped.append(change)

    grouped, issue_conflicts, empty_commits = _group_flat_changes(deduped, raw_flat, unresolved_issue_summary)
    validation = validate_grouped_dataset(grouped)
    summary = _build_5k_summary(
        baseline=baseline,
        new_commits=new_commits,
        raw_flat=raw_flat,
        cleaned_flat=deduped,
        grouped=grouped,
        removed_duplicates=removed_duplicates,
        removed_format_only=removed_format_only,
        unresolved_issue_summary=unresolved_issue_summary,
        entity_type_review=entity_type_review,
        invalid_changes=invalid_changes,
        validation=validation,
        empty_commits=empty_commits,
    )
    return {
        "raw_flat": raw_flat,
        "cleaned_flat": _strip_flat_internal(deduped),
        "grouped": grouped,
        "removed_duplicates": removed_duplicates,
        "removed_empty_commits": empty_commits,
        "removed_format_only": removed_format_only,
        "unresolved_issue_summary": unresolved_issue_summary,
        "entity_type_review": entity_type_review,
        "invalid_changes": invalid_changes,
        "javadoc_format_review": _javadoc_format_review(grouped),
        "issue_summary_conflicts": issue_conflicts,
        "validation": validation,
        "summary": summary,
    }


def _clean_flat_change(change: dict) -> tuple[dict | None, str]:
    required = ("project_slug", "repository_url", "commit_hash", "issue_summary", *CHANGE_FIELDS)
    if not all(field in change for field in required):
        return None, "missing_fields"
    clean = dict(change)
    for field in ("project_slug", "repository_url", "commit_hash", "issue_summary", *CHANGE_FIELDS):
        if field == "change_index":
            continue
        value = clean[field]
        if not isinstance(value, str):
            return None, "non_string_field"
        value = normalize_file_text(value)
        if not value.strip():
            return None, "empty_field"
        clean[field] = value
    if clean["entity_type"] not in {"method", "class"}:
        return None, "unknown_entity_type"
    if clean["code_before"] == clean["code_after"]:
        return None, "identical_code"
    if clean["javadoc_before"] == clean["javadoc_after"]:
        return None, "identical_javadoc"
    before_reason = validate_code_snippet(clean["code_before"], clean["entity_type"])
    after_reason = validate_code_snippet(clean["code_after"], clean["entity_type"])
    if before_reason or after_reason:
        return None, f"invalid_code:{before_reason or after_reason}"
    return clean, ""


def _group_flat_changes(
    changes: list[dict],
    raw_flat: list[dict],
    unresolved_issue_summary: list[dict],
) -> tuple[list[dict], list[dict], list[dict]]:
    raw_commit_keys = OrderedDict(((item["project_slug"], item["commit_hash"]), item) for item in raw_flat)
    by_commit: OrderedDict[tuple[str, str], list[dict]] = OrderedDict()
    for change in changes:
        by_commit.setdefault((change["project_slug"], change["commit_hash"]), []).append(change)
    grouped: list[dict] = []
    issue_conflicts: list[dict] = []
    for (project_slug, commit_hash), group in by_commit.items():
        summaries = [item["issue_summary"] for item in group]
        good_summaries = [summary for summary in summaries if not is_weak_issue_summary(summary)]
        if not good_summaries:
            first = group[0]
            unresolved_issue_summary.append(
                {
                    "project_slug": project_slug,
                    "repository_url": first["repository_url"],
                    "commit_hash": commit_hash,
                    "issue_summary": summaries[0] if summaries else "",
                    "detected": True,
                    "resolved": False,
                    "resolution_source": "",
                    "reason": "weak_issue_summary_unresolved",
                }
            )
            continue
        chosen_summary = good_summaries[0]
        if len(set(summaries)) > 1:
            issue_conflicts.append(
                {
                    "project_slug": project_slug,
                    "commit_hash": commit_hash,
                    "chosen_issue_summary": chosen_summary,
                    "candidate_issue_summaries": sorted(set(summaries)),
                }
            )
        commit = {
            "project_slug": project_slug,
            "repository_url": group[0]["repository_url"],
            "commit_hash": commit_hash,
            "issue_summary": chosen_summary,
            "changes": [],
        }
        for change in group:
            commit["changes"].append(
                {
                    "change_index": len(commit["changes"]) + 1,
                    "entity_type": change["entity_type"],
                    "code_before": change["code_before"],
                    "code_after": change["code_after"],
                    "javadoc_before": change["javadoc_before"],
                    "javadoc_after": change["javadoc_after"],
                }
            )
        grouped.append(commit)

    grouped_keys = {(item["project_slug"], item["commit_hash"]) for item in grouped}
    empty_commits = [
        {
            "project_slug": key[0],
            "repository_url": raw_commit_keys[key].get("repository_url", ""),
            "commit_hash": key[1],
            "removal_reason": "all_changes_removed",
        }
        for key in raw_commit_keys
        if key not in grouped_keys
    ]
    return grouped, issue_conflicts, empty_commits


def _build_5k_summary(
    *,
    baseline: list[dict],
    new_commits: list[dict],
    raw_flat: list[dict],
    cleaned_flat: list[dict],
    grouped: list[dict],
    removed_duplicates: list[dict],
    removed_format_only: list[dict],
    unresolved_issue_summary: list[dict],
    entity_type_review: list[dict],
    invalid_changes: list[dict],
    validation: dict,
    empty_commits: list[dict],
) -> dict:
    change_counts = [len(commit["changes"]) for commit in grouped]
    method_count = sum(1 for commit in grouped for change in commit["changes"] if change["entity_type"] == "method")
    class_count = sum(1 for commit in grouped for change in commit["changes"] if change["entity_type"] == "class")
    per_project_commits = Counter(commit["project_slug"] for commit in grouped)
    per_project_changes = Counter()
    for commit in grouped:
        per_project_changes[commit["project_slug"]] += len(commit["changes"])
    return {
        "baseline_path": "final_dataset_merged_no_commit_cap",
        "baseline_commit_count": len(baseline),
        "baseline_change_count": sum(len(commit.get("changes", [])) for commit in baseline),
        "new_raw_candidate_commit_count": len(new_commits),
        "new_raw_candidate_change_count": sum(len(commit.get("changes", [])) for commit in new_commits),
        "combined_raw_change_count": len(raw_flat),
        "combined_cleaned_change_count": len(cleaned_flat),
        "duplicate_change_count": len(removed_duplicates),
        "empty_commit_removed_count": len(empty_commits),
        "format_only_removed_count": len(removed_format_only),
        "weak_issue_unresolved_count": len(unresolved_issue_summary),
        "entity_type_review_count": len(entity_type_review),
        "invalid_change_count": len(invalid_changes),
        "final_commit_count": len(grouped),
        "final_total_change_count": sum(change_counts),
        "final_method_change_count": method_count,
        "final_class_change_count": class_count,
        "commits_with_one_change": sum(1 for count in change_counts if count == 1),
        "commits_with_multiple_changes": sum(1 for count in change_counts if count > 1),
        "average_changes_per_commit": round(sum(change_counts) / len(change_counts), 4) if change_counts else 0,
        "median_changes_per_commit": median(change_counts) if change_counts else 0,
        "max_changes_in_one_commit": max(change_counts, default=0),
        "per_project_commit_count": dict(sorted(per_project_commits.items())),
        "per_project_change_count": dict(sorted(per_project_changes.items())),
        "validation": validation,
    }


def _write_continuation_top_level(continuation_dir: Path, new_raw: list[dict], merged: dict) -> None:
    _write_json(continuation_dir / "raw_candidates_by_commit.json", new_raw)
    _write_json(continuation_dir / "cleaned_by_commit.json", _new_commits_retained_in_final(new_raw, merged["grouped"]))
    _write_json(continuation_dir / "cleaned_flat.json", _flatten_grouped(_new_commits_retained_in_final(new_raw, merged["grouped"]), "new"))
    for name in (
        "removed_duplicates",
        "removed_format_only",
        "unresolved_issue_summary",
        "entity_type_review",
        "javadoc_format_review",
        "invalid_changes",
    ):
        _write_json(continuation_dir / f"{name}.json", merged[name])
    _write_json(continuation_dir / "validation_report.json", merged["validation"])
    (continuation_dir / "README.md").write_text(_render_continuation_readme(merged["summary"]), encoding="utf-8")


def _write_final_outputs(
    final_dir: Path,
    merged: dict,
    continuation_dir: Path,
    baseline_dir: Path,
    legacy_merged_dir: Path,
    config: CommitContinuationConfig,
) -> None:
    final_dir.mkdir(parents=True, exist_ok=True)
    _write_json(final_dir / "combined_raw_flat.json", _strip_flat_internal(merged["raw_flat"]))
    _write_json(final_dir / "combined_cleaned_flat.json", merged["cleaned_flat"])
    _write_json(final_dir / "combined_by_commit.json", merged["grouped"])
    for name in (
        "removed_duplicates",
        "removed_empty_commits",
        "removed_format_only",
        "unresolved_issue_summary",
        "entity_type_review",
        "invalid_changes",
        "javadoc_format_review",
        "validation_report",
        "summary",
    ):
        key = "validation" if name == "validation_report" else name
        _write_json(final_dir / f"{name}.json", merged[key])
    _write_summary_csv(final_dir / "summary.csv", merged["summary"])
    _copy_if_exists(continuation_dir / "repository_yield_summary.json", final_dir / "repository_yield_summary.json", [])
    _copy_if_exists(continuation_dir / "repository_yield_summary.csv", final_dir / "repository_yield_summary.csv", "")
    _copy_if_exists(continuation_dir / "scan_progress.json", final_dir / "scan_progress.json", [])
    _copy_if_exists(continuation_dir / "scan_progress.csv", final_dir / "scan_progress.csv", "")
    _copy_if_exists(continuation_dir / "failed_repositories.json", final_dir / "failed_repositories.json", [])
    _copy_if_exists(
        continuation_dir / "stopped_low_yield_repositories.json",
        final_dir / "stopped_low_yield_repositories.json",
        [],
    )
    _copy_if_exists(continuation_dir / "scanned_repositories.json", final_dir / "scanned_repositories.json", [])
    _copy_if_exists(continuation_dir / "scanned_commits.json", final_dir / "scanned_commits.json", {})
    _write_source_backups(final_dir, baseline_dir, legacy_merged_dir, continuation_dir)
    (final_dir / "README.md").write_text(_render_final_readme(merged["summary"], config), encoding="utf-8")


def _write_source_backups(final_dir: Path, baseline_dir: Path, legacy_merged_dir: Path, continuation_dir: Path) -> None:
    backup_root = final_dir / "source_backups"
    backup_root.mkdir(parents=True, exist_ok=True)
    for source_dir in (legacy_merged_dir, baseline_dir, continuation_dir):
        if not source_dir.exists():
            continue
        target = backup_root / source_dir.name
        target.mkdir(parents=True, exist_ok=True)
        for file_name in (
            "combined_by_commit.json",
            "combined_cleaned_flat.json",
            "summary.json",
            "summary.csv",
            "validation_report.json",
            "README.md",
            "cleaned_by_commit.json",
            "raw_candidates_by_commit.json",
            "scan_progress.json",
            "repository_yield_summary.json",
        ):
            source = source_dir / file_name
            if source.exists():
                try:
                    shutil.copy2(source, target / file_name)
                except OSError as error:
                    _append_json_list(
                        backup_root / "backup_warnings.json",
                        {
                            "source": str(source),
                            "target": str(target / file_name),
                            "reason": str(error),
                        },
                    )
    _write_json(backup_root / "scan_repository_order.json", [_spec_dict(spec) for spec in PRIORITY_REPOSITORIES])
    _write_json(backup_root / "run_config.json", _config_dict_for_json())
    try:
        import subprocess

        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=Path(__file__).resolve().parents[1],
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode == 0:
            (backup_root / "code_git_commit.txt").write_text(result.stdout.strip() + "\n", encoding="utf-8")
    except OSError:
        pass


def _write_project_commit_files(project_dir: Path, commits: list[dict]) -> None:
    commits = sorted(commits, key=lambda item: item["commit_hash"])
    _write_json(project_dir / "raw_candidates_by_commit.json", commits)
    _write_json(project_dir / "cleaned_by_commit.json", commits)
    _write_json(project_dir / "cleaned_flat.json", _flatten_grouped(commits, "new"))


def _record_scan_progress(
    continuation_dir: Path,
    spec: RepositorySpec,
    counters: ProjectCounters,
    outputs: dict,
    batch_index: int,
    commits_scanned_in_batch: int,
    scan_status: str,
    stop_reason: str,
) -> None:
    retained_after = _retained_new_counts_for_project(outputs["grouped"], spec.slug)
    row = {
        "project_slug": spec.slug,
        "repository_url": spec.url,
        "batch_index": batch_index,
        "commits_scanned": commits_scanned_in_batch,
        "cumulative_commits_scanned": counters.commits_scanned,
        "raw_candidate_commits": counters.raw_candidate_commits,
        "raw_candidate_changes": counters.raw_candidate_changes,
        "retained_commits_before_global_dedup": counters.retained_commits_before_global_dedup,
        "retained_commits_after_global_dedup": retained_after["commits"],
        "retained_changes_before_global_dedup": counters.retained_changes_before_global_dedup,
        "retained_changes_after_global_dedup": retained_after["changes"],
        "method_level_changes": counters.method_level_changes,
        "class_level_changes": counters.class_level_changes,
        "commits_with_multiple_changes": counters.commits_with_multiple_changes,
        "duplicate_changes_removed": outputs["summary"]["duplicate_change_count"],
        "empty_commits_removed": outputs["summary"]["empty_commit_removed_count"],
        "format_only_rejection_count": counters.format_only_rejection_count,
        "weak_issue_detected": counters.weak_issue_detected,
        "weak_issue_resolved": counters.weak_issue_resolved,
        "weak_issue_unresolved": counters.weak_issue_unresolved,
        "java_parse_success_count": counters.java_parse_success_count,
        "java_parse_failure_count": counters.java_parse_failure_count,
        "issue_summary_success_rate": _rate(counters.weak_issue_resolved, counters.weak_issue_detected),
        "java_parse_success_rate": _rate(
            counters.java_parse_success_count,
            counters.java_parse_success_count + counters.java_parse_failure_count,
        ),
        "yield_per_1000_scanned_commits": _yield_per_1000(counters),
        "oldest_commit": counters.oldest_commit,
        "newest_commit": counters.newest_commit,
        "scan_status": scan_status,
        "stop_reason": stop_reason,
    }
    records = _read_json(continuation_dir / "scan_progress.json", [])
    if not isinstance(records, list):
        records = []
    records.append(row)
    _write_json(continuation_dir / "scan_progress.json", records)
    _write_csv(continuation_dir / "scan_progress.csv", records, BATCH_FIELDS)
    _update_scanned_repository_records(continuation_dir, spec, counters, scan_status, stop_reason)


def _record_skipped_repository(continuation_dir: Path, spec: RepositorySpec, metadata: dict) -> None:
    row = {
        "project_slug": spec.slug,
        "repository_url": spec.url,
        "scan_started_at": "",
        "scan_completed_at": _utc_now(),
        "scanned_commit_count": 0,
        "retained_commit_count": 0,
        "retained_change_count": 0,
        "oldest_scanned_commit": "",
        "newest_scanned_commit": "",
        "scan_status": "skipped",
        "stop_reason": f"already_completed:{metadata.get('source', 'existing_dataset')}",
    }
    _upsert_by_key(continuation_dir / "scanned_repositories.json", row, "project_slug")
    _update_repository_yield_summary(continuation_dir)


def _update_scanned_repository_records(
    continuation_dir: Path,
    spec: RepositorySpec,
    counters: ProjectCounters,
    scan_status: str,
    stop_reason: str,
) -> None:
    retained = _read_json(continuation_dir / "per_project" / spec.slug / "cleaned_by_commit.json", [])
    retained = retained if isinstance(retained, list) else []
    row = {
        "project_slug": spec.slug,
        "repository_url": spec.url,
        "scan_started_at": "",
        "scan_completed_at": _utc_now() if scan_status in {"completed", "stopped", "skipped"} else "",
        "scanned_commit_count": counters.commits_scanned,
        "retained_commit_count": len(retained),
        "retained_change_count": sum(len(item.get("changes", [])) for item in retained),
        "oldest_scanned_commit": counters.oldest_commit,
        "newest_scanned_commit": counters.newest_commit,
        "scan_status": scan_status,
        "stop_reason": stop_reason,
    }
    _upsert_by_key(continuation_dir / "scanned_repositories.json", row, "project_slug")
    _remove_failed_repository(continuation_dir, spec.slug)
    scanned = _read_json(continuation_dir / "scanned_commits.json", {})
    if not isinstance(scanned, dict):
        scanned = {}
    checkpoint = _read_json(continuation_dir / "per_project" / spec.slug / "checkpoint.json", {})
    scanned[spec.slug] = checkpoint.get("processed_commit_hashes", [])
    _write_json(continuation_dir / "scanned_commits.json", scanned)


def _remove_failed_repository(continuation_dir: Path, project_slug: str) -> None:
    path = continuation_dir / "failed_repositories.json"
    rows = _read_json(path, [])
    if not isinstance(rows, list):
        return
    rows = [row for row in rows if not isinstance(row, dict) or row.get("project_slug") != project_slug]
    _write_json(path, rows)


def _update_repository_yield_summary(continuation_dir: Path) -> None:
    repos = _read_json(continuation_dir / "scanned_repositories.json", [])
    if not isinstance(repos, list):
        repos = []
    _prune_resolved_failures(continuation_dir, repos)
    progress = _read_json(continuation_dir / "scan_progress.json", [])
    latest_progress: dict[str, dict] = {}
    if isinstance(progress, list):
        for row in progress:
            if isinstance(row, dict) and row.get("project_slug"):
                latest_progress[row["project_slug"]] = row
    rows = []
    for repo in repos:
        latest = latest_progress.get(repo.get("project_slug", ""))
        scanned = int(
            (latest or {}).get("cumulative_commits_scanned", repo.get("scanned_commit_count", 0))
            or 0
        )
        retained = int(
            (latest or {}).get("retained_commits_after_global_dedup", repo.get("retained_commit_count", 0))
            or 0
        )
        retained_changes = int(
            (latest or {}).get("retained_changes_after_global_dedup", repo.get("retained_change_count", 0))
            or 0
        )
        rows.append(
            {
                **repo,
                "scanned_commit_count": scanned,
                "retained_commit_count": retained,
                "retained_change_count": retained_changes,
                "yield_per_1000_scanned_commits": round(retained / scanned * 1000, 4) if scanned else 0,
            }
        )
    _write_json(continuation_dir / "repository_yield_summary.json", rows)
    fields = [
        "project_slug",
        "repository_url",
        "scanned_commit_count",
        "retained_commit_count",
        "retained_change_count",
        "yield_per_1000_scanned_commits",
        "scan_status",
        "stop_reason",
    ]
    _write_csv(continuation_dir / "repository_yield_summary.csv", rows, fields)


def _prune_resolved_failures(continuation_dir: Path, repos: list[dict]) -> None:
    resolved = {
        repo.get("project_slug")
        for repo in repos
        if isinstance(repo, dict) and int(repo.get("scanned_commit_count", 0) or 0) > 0
    }
    if not resolved:
        return
    path = continuation_dir / "failed_repositories.json"
    failures = _read_json(path, [])
    if not isinstance(failures, list):
        return
    failures = [
        failure
        for failure in failures
        if not isinstance(failure, dict) or failure.get("project_slug") not in resolved
    ]
    _write_json(path, failures)


def _save_checkpoint(
    project_dir: Path,
    spec: RepositorySpec,
    checkpoint: dict,
    counters: ProjectCounters,
    processed: set[str],
    last_processed_commit: str,
    current_batch: int,
    scan_status: str,
    stop_reason: str,
) -> None:
    checkpoint.update(
        {
            "project_slug": spec.slug,
            "repository_url": spec.url,
            "branch": "HEAD",
            "last_processed_commit": last_processed_commit or checkpoint.get("last_processed_commit", ""),
            "processed_commit_hashes": sorted(processed),
            "current_batch": current_batch,
            "raw_candidate_commits": counters.raw_candidate_commits,
            "raw_candidate_changes": counters.raw_candidate_changes,
            "cleaned_commit_count": counters.retained_commits_before_global_dedup,
            "cleaned_change_count": counters.retained_changes_before_global_dedup,
            "scan_status": scan_status,
            "stop_reason": stop_reason,
            "counters": counters.__dict__,
            "updated_at_utc": _utc_now(),
        }
    )
    _write_json(project_dir / "checkpoint.json", checkpoint)


def _load_project_counters(checkpoint: dict) -> ProjectCounters:
    value = checkpoint.get("counters", {})
    counters = ProjectCounters()
    if isinstance(value, dict):
        for field in counters.__dict__:
            if field in value:
                setattr(counters, field, value[field])
    return counters


def _should_stop_low_yield(
    counters: ProjectCounters,
    initial_probe_commits: int,
    retained_after_global_dedup: int,
) -> bool:
    if counters.commits_scanned < initial_probe_commits:
        return False
    if counters.commits_scanned == 0:
        return False
    return retained_after_global_dedup / counters.commits_scanned * 1000 < LOW_YIELD_THRESHOLD


def _yield_per_1000(counters: ProjectCounters) -> float:
    if counters.commits_scanned == 0:
        return 0.0
    return round(counters.retained_commits_before_global_dedup / counters.commits_scanned * 1000, 4)


def _retained_new_counts_for_project(grouped: list[dict], slug: str) -> dict[str, int]:
    project_commits = [commit for commit in grouped if commit.get("project_slug") == slug]
    return {
        "commits": len(project_commits),
        "changes": sum(len(commit.get("changes", [])) for commit in project_commits),
    }


def _path_allowed_for_project(project_name: str, path: str) -> bool:
    normalized = path.replace("\\", "/")
    lower = normalized.lower()
    if project_name == "grpc/grpc-java":
        if any(part in lower for part in ("/examples/", "/interop-testing/", "/benchmarks/", "/testing-proto/")):
            return False
        if "generated" in lower or lower.endswith("grpc.java") or lower.endswith("proto.java"):
            return False
    if project_name == "netty/netty":
        allowed = ("buffer/", "codec/", "codec-http/", "codec-http2/", "common/", "handler/", "transport/", "resolver/")
        if not lower.startswith(allowed):
            return False
    if project_name == "apache/avro" and not lower.startswith("lang/java/"):
        return False
    if project_name == "apache/kafka" and not lower.startswith("clients/src/main/java/"):
        return False
    if project_name == "jOOQ/jOOQ" and any(part in lower for part in ("/generated/", "/codegen/", "/meta/")):
        return False
    return True


def _is_generated_source(content: str | None) -> bool:
    if not content:
        return False
    header = "\n".join(content.splitlines()[:40]).lower()
    return any(token in header for token in PRODUCTION_HEADERS)


def _is_metadata_only_commit_message(commit_message: str) -> bool:
    normalized = " ".join(commit_message.lower().split())
    return any(token in normalized for token in METADATA_ONLY_COMMIT_SUBSTRINGS)


def _commit_hashes(repo: GitRepo) -> list[str]:
    return [line for line in repo.run_git(["rev-list", "HEAD"]).splitlines() if line]


def _flatten_grouped(grouped: list[dict], dataset: str) -> list[dict]:
    flat: list[dict] = []
    for commit_index, commit in enumerate(grouped):
        for change in commit.get("changes", []):
            flat.append(
                {
                    "project_slug": commit.get("project_slug", ""),
                    "repository_url": commit.get("repository_url", ""),
                    "commit_hash": commit.get("commit_hash", ""),
                    "issue_summary": commit.get("issue_summary", ""),
                    "change_index": change.get("change_index", 0),
                    "entity_type": change.get("entity_type", ""),
                    "code_before": change.get("code_before", ""),
                    "code_after": change.get("code_after", ""),
                    "javadoc_before": change.get("javadoc_before", ""),
                    "javadoc_after": change.get("javadoc_after", ""),
                    "_dataset": dataset,
                    "_source_order": len(flat),
                    "_source_commit_order": commit_index,
                }
            )
    return flat


def _strip_flat_internal(changes: list[dict]) -> list[dict]:
    keys = ("project_slug", "repository_url", "commit_hash", "issue_summary", "entity_type", "code_before", "code_after", "javadoc_before", "javadoc_after")
    return [{key: change.get(key, "") for key in keys} for change in changes]


def _new_commits_retained_in_final(new_raw: list[dict], final_grouped: list[dict]) -> list[dict]:
    final_keys = {(commit["project_slug"], commit["commit_hash"]) for commit in final_grouped}
    new_keys = {(commit["project_slug"], commit["commit_hash"]) for commit in new_raw}
    retained = []
    for commit in final_grouped:
        key = (commit["project_slug"], commit["commit_hash"])
        if key in new_keys and key in final_keys:
            retained.append(commit)
    return retained


def _load_all_project_commits(continuation_dir: Path) -> list[dict]:
    commits: list[dict] = []
    per_project = continuation_dir / "per_project"
    if not per_project.exists():
        return commits
    for path in sorted(per_project.iterdir()):
        if not path.is_dir():
            continue
        value = _load_grouped_dataset(path / "cleaned_by_commit.json")
        commits.extend(value)
    return commits


def _load_grouped_dataset(path: Path) -> list[dict]:
    value = _read_json(path, [])
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict) and isinstance(item.get("changes"), list)]


def _completed_existing_repositories(root_dir: Path) -> dict[str, dict]:
    completed: dict[str, dict] = {}
    for dataset_name in ("final_dataset", "final_dataset_extra_3k"):
        dataset_dir = root_dir / dataset_name
        if not dataset_dir.exists():
            continue
        for project_dir in dataset_dir.iterdir():
            if not project_dir.is_dir():
                continue
            metadata = _read_json(project_dir / "metadata.json", {})
            if isinstance(metadata, dict) and metadata.get("complete_history"):
                metadata = dict(metadata)
                metadata["source"] = dataset_name
                completed[project_dir.name] = metadata
    return completed


def _selected_repositories(
    repositories: list[RepositorySpec],
    start_from: str,
    max_repos: int | None,
) -> list[RepositorySpec]:
    if start_from:
        start_slug = repository_slug(start_from)
        start_index = next(
            (
                index
                for index, spec in enumerate(repositories)
                if start_from in {spec.name, spec.slug} or start_slug == spec.slug
            ),
            None,
        )
        if start_index is None:
            raise ValueError(f"Unknown start repository: {start_from}")
        repositories = repositories[start_index:]
    if max_repos is not None:
        repositories = repositories[:max_repos]
    return repositories


def _ensure_run_files(continuation_dir: Path) -> None:
    continuation_dir.mkdir(parents=True, exist_ok=True)
    (continuation_dir / "per_project").mkdir(parents=True, exist_ok=True)
    defaults = {
        "scan_progress.json": [],
        "repository_yield_summary.json": [],
        "failed_repositories.json": [],
        "stopped_low_yield_repositories.json": [],
        "scanned_repositories.json": [],
        "scanned_commits.json": {},
        "removed_duplicates.json": [],
        "removed_format_only.json": [],
        "unresolved_issue_summary.json": [],
        "entity_type_review.json": [],
        "javadoc_format_review.json": [],
        "invalid_changes.json": [],
    }
    for file_name, value in defaults.items():
        path = continuation_dir / file_name
        if not path.exists():
            _write_json(path, value)


def _javadoc_format_review(grouped: list[dict]) -> list[dict]:
    review: list[dict] = []
    for commit in grouped:
        for change in commit["changes"]:
            for field in ("javadoc_before", "javadoc_after"):
                value = change[field]
                reasons = []
                if "\ufffd" in value:
                    reasons.append("replacement_character")
                if value.strip().startswith("/**") and not value.strip().endswith("*/"):
                    reasons.append("unclosed_javadoc")
                if value.count("<") != value.count(">"):
                    reasons.append("unbalanced_angle_brackets")
                if reasons:
                    review.append(
                        {
                            "project_slug": commit["project_slug"],
                            "commit_hash": commit["commit_hash"],
                            "change_index": change["change_index"],
                            "field": field,
                            "reasons": reasons,
                        }
                    )
    return review


def _audit_removed_change(change: dict, reason: str) -> dict:
    return {
        "project_slug": change.get("project_slug", ""),
        "repository_url": change.get("repository_url", ""),
        "commit_hash": change.get("commit_hash", ""),
        "change_index": change.get("change_index", 0),
        "duplicate_of": "",
        "removal_reason": reason,
    }


def _change_ref(change: dict) -> dict:
    return {
        "project_slug": change.get("project_slug", ""),
        "commit_hash": change.get("commit_hash", ""),
        "change_index": change.get("change_index", 0),
    }


def _repository_yield_row(
    spec: RepositorySpec,
    counters: ProjectCounters,
    scan_status: str,
    stop_reason: str,
    retained_commits_after_global_dedup: int | None = None,
    retained_changes_after_global_dedup: int | None = None,
) -> dict:
    retained_commits = (
        counters.retained_commits_before_global_dedup
        if retained_commits_after_global_dedup is None
        else retained_commits_after_global_dedup
    )
    retained_changes = (
        counters.retained_changes_before_global_dedup
        if retained_changes_after_global_dedup is None
        else retained_changes_after_global_dedup
    )
    return {
        "project_slug": spec.slug,
        "repository_url": spec.url,
        "scanned_commit_count": counters.commits_scanned,
        "retained_commit_count": retained_commits,
        "retained_change_count": retained_changes,
        "yield_per_1000_scanned_commits": round(retained_commits / counters.commits_scanned * 1000, 4)
        if counters.commits_scanned
        else 0,
        "scan_status": scan_status,
        "stop_reason": stop_reason,
    }


def _render_continuation_readme(summary: dict) -> str:
    return f"""# 5k Commit Continuation Dataset

This directory stores only newly mined commit-level candidates for extending
the Patch-Aware Javadoc Updating dataset. It does not overwrite the accepted
baseline.

The target is counted by unique valid commits, not by changes.

- New raw candidate commits: {summary['new_raw_candidate_commit_count']}
- New raw candidate changes: {summary['new_raw_candidate_change_count']}
- Final merged commits so far: {summary['final_commit_count']}
- Final merged changes so far: {summary['final_total_change_count']}
- Validation passed: {summary['validation']['passed']}
"""


def _render_final_readme(summary: dict, config: CommitContinuationConfig) -> str:
    return f"""# 5k Commit Patch-Aware Javadoc Updating Dataset

This directory is the commit-level merged view for the Patch-Aware Javadoc
Updating task.

Input fields for each change are `issue_summary`, `code_before`, `code_after`,
and `javadoc_before`. The target field is `javadoc_after`.

The target is **at least {config.target_commits} unique valid commits**, where a
unique commit is `project_slug + commit_hash`. Changes are additional
statistics and are not the stop condition.

## Sources

- Effective baseline: `final_dataset_merged_no_commit_cap`
- Legacy capped merged dataset preserved for audit: `final_dataset_merged`
- New continuation candidates: `final_dataset_continuation_to_5k_commits`

## Final Counts

- Final commits: {summary['final_commit_count']}
- Final changes: {summary['final_total_change_count']}
- Method-level changes: {summary['final_method_change_count']}
- Class-level changes: {summary['final_class_change_count']}
- Commits with one change: {summary['commits_with_one_change']}
- Commits with multiple changes: {summary['commits_with_multiple_changes']}
- Average changes per commit: {summary['average_changes_per_commit']}
- Median changes per commit: {summary['median_changes_per_commit']}
- Max changes in one commit: {summary['max_changes_in_one_commit']}
- Validation passed: {summary['validation']['passed']}

## Cleaning

Changes are deduplicated globally by exact content fingerprint over
`code_before`, `code_after`, `javadoc_before`, and `javadoc_after`. Commits
whose changes are all removed are removed from the final commit count. Weak
issue summaries are not generated by a model; unresolved weak summaries are
excluded.

## Max-3 Audit

The active baseline is the no-cap merged dataset. It already contains commits
with more than 3 changes, and this continuation flow does not truncate changes
per commit.

## Resume

```powershell
python -m javadoc_miner mine-5k-commits `
  --baseline-dir final_dataset_merged_no_commit_cap `
  --continuation-dir final_dataset_continuation_to_5k_commits `
  --final-dir final_dataset_5k_commits `
  --target-commits {config.target_commits}
```
"""


def _write_summary_csv(path: Path, summary: dict) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["metric", "value"])
        for key, value in summary.items():
            if isinstance(value, (dict, list)):
                writer.writerow([key, json.dumps(value, ensure_ascii=False, sort_keys=True)])
            else:
                writer.writerow([key, value])


def _write_csv(path: Path, rows: list[dict], fields: Iterable[str]) -> None:
    fields = list(fields)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def _append_json_list(path: Path, item: dict) -> None:
    rows = _read_json(path, [])
    if not isinstance(rows, list):
        rows = []
    rows.append(item)
    _write_json(path, rows)


def _upsert_by_key(path: Path, row: dict, key: str) -> None:
    rows = _read_json(path, [])
    if not isinstance(rows, list):
        rows = []
    rows = [item for item in rows if not isinstance(item, dict) or item.get(key) != row.get(key)]
    rows.append(row)
    _write_json(path, rows)


def _copy_if_exists(source: Path, target: Path, default) -> None:
    if source.exists():
        shutil.copy2(source, target)
    elif isinstance(default, str):
        target.write_text(default, encoding="utf-8")
    else:
        _write_json(target, default)


def _read_json(path: Path, default):
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError):
        return default


def _write_json(path: Path, value) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(value, ensure_ascii=False, indent=2)
    last_error: OSError | None = None
    for attempt in range(5):
        temp_path = path.with_name(f".{path.name}.{os.getpid()}.{attempt}.tmp")
        try:
            temp_path.write_text(text, encoding="utf-8")
            try:
                temp_path.replace(path)
                return
            except OSError:
                try:
                    if path.exists():
                        path.unlink()
                    temp_path.replace(path)
                    return
                except OSError:
                    path.write_text(text, encoding="utf-8")
                    return
        except OSError as error:
            last_error = error
            try:
                if temp_path.exists():
                    temp_path.unlink()
            except OSError:
                pass
            time.sleep(0.2 * (attempt + 1))
    if last_error is not None:
        raise last_error


def _resolve(root_dir: Path, path: Path) -> Path:
    return path if path.is_absolute() else root_dir / path


def _rate(numerator: int, denominator: int) -> float:
    return round(numerator / denominator, 4) if denominator else 1.0


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _spec_dict(spec: RepositorySpec) -> dict:
    return {"project_slug": spec.slug, "repository_url": spec.url, "repository_name": spec.name}


def _config_dict_for_json() -> dict:
    return {
        "priority_repositories": [_spec_dict(spec) for spec in PRIORITY_REPOSITORIES],
        "low_yield_threshold_per_1000_commits": LOW_YIELD_THRESHOLD,
        "high_yield_threshold_per_1000_commits": HIGH_YIELD_THRESHOLD,
    }
